apiVersion: v1
kind: Service
metadata:
  name:  balli-rtp-service
  namespace: balli
spec:
  type: NodePort
  selector:
    app: balli-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
